services:
  - type: web
    name: resume-backend
    env: node
    plan: free
    autoDeploy: true
    buildCommand: ""
    startCommand: node server/index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: DB_NAME
        value: resume_builder
      - key: PORT
        value: 4000
