apiVersion: apps/v1
kind: Deployment
metadata:
  name: resume-builder-app
  namespace: jenkins
spec:
  replicas: 1
  selector:
    matchLabels:
      app: resume-builder-app
  template:
    metadata:
      labels:
        app: resume-builder-app
    spec:
      containers:
        - name: resume-builder-app
          image: nexus-service-for-docker-hosted-registry.nexus.svc.cluster.local:8085/my-repository/resume-builder-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
      imagePullSecrets:
        - name: nexus-docker-secret
